$(".btn-classe01").click(function(){
    $(".check-classe01").css("display","block");
});
$(".btn-classe02").click(function(){
    $(".check-classe02").css("display","block");
});
$(".btn-classe03").click(function(){
    $(".check-classe03").css("display","block");
});
$(".btn-classe04").click(function(){
    $(".check-classe04").css("display","block");
});
$(".btn-classe05").click(function(){
    $(".check-classe05").css("display","block");
});
$(".btn-classe06").click(function(){
    $(".check-classe06").css("display","block");
});
$(".btn-classe07").click(function(){
    $(".check-classe07").css("display","block");
});


$(".btn-aspecto01").click(function(){
    $(".check-aspecto01").css("display","block");
});
$(".btn-aspecto02").click(function(){
    $(".check-aspecto02").css("display","block");
});
$(".btn-aspecto03").click(function(){
    $(".check-aspecto03").css("display","block");
});
$(".btn-aspecto04").click(function(){
    $(".check-aspecto04").css("display","block");
});
$(".btn-aspecto05").click(function(){
    $(".check-aspecto05").css("display","block");
});