$(".btn-demanda").click(function(){
    $(".check-demanda").css("display","block");
});
$(".btn-aplicacao").click(function(){
    $(".check-aplicacao").css("display","block");
});
$(".btn-criticidade").click(function(){
    $(".check-criticidade").css("display","block");
});
$(".btn-perecibilidade").click(function(){
    $(".check-perecibilidade").css("display","block");
});
$(".btn-periculosidade").click(function(){
    $(".check-periculosidade").css("display","block");
});
$(".btn-fabricacao").click(function(){
    $(".check-fabricacao").css("display","block");
});
$(".btn-condicao").click(function(){
    $(".check-condicao").css("display","block");
});
$(".btn-movimentacao").click(function(){
    $(".check-movimentacao").css("display","block");
});

$(".btn-aspecto01").click(function(){
    $(".check-aspecto01").css("display","block");
});
$(".btn-aspecto02").click(function(){
    $(".check-aspecto02").css("display","block");
});
$(".btn-aspecto03").click(function(){
    $(".check-aspecto03").css("display","block");
});
$(".btn-aspecto04").click(function(){
    $(".check-aspecto04").css("display","block");
});
$(".btn-aspecto05").click(function(){
    $(".check-aspecto05").css("display","block");
});